apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-specimen-data-quality-annotation
  labels:
    app: digital-specimen-data-quality-annotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-specimen-data-quality-annotation
  template:
    metadata:
      labels:
        app: digital-specimen-data-quality-annotation
    spec:
      containers:
        - name: digital-specimen-data-quality-annotation
          image: public.ecr.aws/dissco/digital-specimen-data-quality-annotation
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_CONSUMER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_PRODUCER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_CONSUMER_TOPIC
              value: digital-specimen-data-quality-annotation
            - name: KAFKA_PRODUCER_TOPIC
              value: annotation
            - name: KAFKA_CONSUMER_GROUP
              value: group
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: digital-specimen-data-quality-annotation-scaled-object
spec:
  scaleTargetRef:
    name:  digital-specimen-data-quality-annotation
  minReplicaCount: 1
  maxReplicaCount:  1
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc.cluster.local:9092
      consumerGroup: group
      topic: digital-specimen-data-quality-annotation
      lagThreshold: '5'
