apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrichment-service-plant-organ-detection
  labels:
    app: enrichment-service-plant-organ-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrichment-service-plant-organ-detection
  template:
    metadata:
      labels:
        app: enrichment-service-plant-organ-detection
    spec:
      containers:
        - name: enrichment-service-plant-organ-detection
          image: leeflangjs/enrichment-service-plant-organ-detection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_CONSUMER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_PRODUCER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_CONSUMER_TOPIC
              value: plant-organ-detection
            - name: KAFKA_PRODUCER_TOPIC
              value: topic-multi
            - name: KAFKA_CONSUMER_GROUP
              value: group
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: enrichment-service-plant-organ-detection-scaled-object
spec:
  scaleTargetRef:
    name:  enrichment-service-plant-organ-detection
  minReplicaCount: 0
  maxReplicaCount:  1
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc.cluster.local:9092
      consumerGroup: group
      topic: plant-organ-detection
      lagThreshold: '5'
