apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrichment-service-image-metadata
  labels:
    app: enrichment-service-image-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrichment-service-image-metadata
  template:
    metadata:
      labels:
        app: enrichment-service-image-metadata
    spec:
      containers:
        - name: enrichment-service-image-metadata
          image: leeflangjs/enrichment-service-image-metadata
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KAFKA_CONSUMER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_PRODUCER_HOST
              value: kafka.kafka.svc.cluster.local:9092
            - name: KAFKA_PRODUCER_TOPIC
              value: topic-multi
            - name: KAFKA_CONSUMER_GROUP
              value: group
            - name: KAFKA_CONSUMER_TOPIC
              value: image_metadata
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: enrichment-service-image-metadata-scaled-object
spec:
  scaleTargetRef:
    name: enrichment-service-image-metadata
  minReplicaCount: 0
  maxReplicaCount:  1
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.kafka.svc.cluster.local:9092
      consumerGroup: group
      topic: image_metadata
      lagThreshold: '5'
