name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker push
        uses: docker/build-push-action@v2
        with:
          context: ./image-metadata-addition/
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo-enrichtment-service-image:latest
